/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WjhGrid {
    }
    interface WjhHome {
    }
}
declare global {
    interface HTMLWjhGridElement extends Components.WjhGrid, HTMLStencilElement {
    }
    var HTMLWjhGridElement: {
        prototype: HTMLWjhGridElement;
        new (): HTMLWjhGridElement;
    };
    interface HTMLWjhHomeElement extends Components.WjhHome, HTMLStencilElement {
    }
    var HTMLWjhHomeElement: {
        prototype: HTMLWjhHomeElement;
        new (): HTMLWjhHomeElement;
    };
    interface HTMLElementTagNameMap {
        "wjh-grid": HTMLWjhGridElement;
        "wjh-home": HTMLWjhHomeElement;
    }
}
declare namespace LocalJSX {
    interface WjhGrid {
    }
    interface WjhHome {
    }
    interface IntrinsicElements {
        "wjh-grid": WjhGrid;
        "wjh-home": WjhHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wjh-grid": LocalJSX.WjhGrid & JSXBase.HTMLAttributes<HTMLWjhGridElement>;
            "wjh-home": LocalJSX.WjhHome & JSXBase.HTMLAttributes<HTMLWjhHomeElement>;
        }
    }
}
